extends: airbnb
env:
  browser: true
globals:
  chrome: true
  React: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  jsx-a11y/heading-has-content: disable
  react/jsx-indent: disabled
  react/sort-comp: disabled
  react/destructuring-assignment: never
  import/no-unresolved:
  - 2
  - ignore:
    - ^\$
